name: three_commas_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ben <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^2.2.0
  http: ^0.12.0
  crypto: ^2.0.6
  json_serializable: ^2.2.2

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.1.3
  json_serializable: ^2.0.2 # flutter packages pub run build_runner build --delete-conflicting-outputs
  #coverage: 0.12.1